name: lokiRankup
version: 1.0.0
main: com.loki.lokirankup.main
commands:
  ranks:
  rankupreload:
    aliases: [configreload]
    permission: rankup.*
  resetmine:
    aliases: [minereset]
  g:
    aliases: [ global ]
  chat:
  npc:
  home:
    aliases: [casa]
  sethome:
    aliases: [setcasa]
  delhome:
    aliases: [ delcasa, deletehome, deletarcasa ]
  publica:
